version: '2'

services:
  thumbor:
    image: apsl/thumbor
  fake-s3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
  postgres:
    image: postgres:9-alpine
    environment:
      - POSTGRES_PASSWORD=K851xsSffyTJP3e1M7rd
  menus:
    image: munch-core/munch-service-places-menu
    environment:
      - MENU_PERSIST_PROVIDER=fake

      - MENU_THUMBOR_ENDPOINT=http://thumbor:8000
      - MENU_FAKE_S3_ENDPOINT=http://fake-s3:4569
      - MENU_FAKE_S3_PUBLIC_ENDPOINT=http://localhost:4569
      
      - MENU_DATABASE_URL=jdbc:postgresql://postgres:5432/postgres
      - MENU_DATABASE_USERNAME=postgres
      - MENU_DATABASE_PASSWORD=K851xsSffyTJP3e1M7rd
      - MENU_DATABASE_AUTO_CREATE=true
    ports:
      - "8004:8000"
    links:
      - thumbor
      - fake-s3
      - postgres