package com.munch.core.struct.block.source;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.munch.core.struct.block.BlockVersion;
import org.apache.commons.lang.StringUtils;

import java.beans.Transient;

/**
 * Source Location are data generated by the spaghetti location entry
 * <p>
 * Created By: Fuxing Loh
 * Date: 14/9/2016
 * Time: 8:26 PM
 * Project: struct
 */
public class SourceLocation extends BlockVersion {

    private String name;
    private String address;

    private String unitNumber;
    private String zipCode;

    private String street;
    private String town;
    private String blk;

    private String countryCode;

    private double lat, lng;

    /**
     * All data should be named with the version that is introduced
     * For data not named, it is there since VERSION_FIRST
     */
    public SourceLocation() {
        super(VERSION_FIRST);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getUnitNumber() {
        return unitNumber;
    }

    public void setUnitNumber(String unitNumber) {
        this.unitNumber = unitNumber;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public double getLat() {
        return lat;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

    public double getLng() {
        return lng;
    }

    public void setLng(double lng) {
        this.lng = lng;
    }

    public String getTown() {
        return town;
    }

    public void setTown(String town) {
        this.town = town;
    }

    public String getBlk() {
        return blk;
    }

    public void setBlk(String blk) {
        this.blk = blk;
    }

    @Transient
    @JsonIgnore
    public String getFormattedAddress() {
        String address = "";

        if (getBlk() != null) {
            address += getBlk() + " ";
        }

        if (getTown() != null) {
            address += getTown() + " ";
        }

        if (getStreet() != null) {
            address += getStreet() + " ";
        }

        if (getUnitNumber() != null) {
            address += getUnitNumber() + " ";
        }

        if (getZipCode() != null) {
            address += getZipCode() + " ";
        }
        return StringUtils.trimToNull(address);
    }
}
