package com.munch.core.struct.block.source;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.munch.core.struct.block.BlockVersion;
import org.apache.commons.lang3.StringUtils;

import java.beans.Transient;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Source Place are places generated by the probe and extractor
 * <p>
 * Created By: Fuxing Loh
 * Date: 26/8/2016
 * Time: 5:27 PM
 * Project: struct
 */
public class SourcePlace extends BlockVersion {

    // Basic
    private String name;
    private long fanCount;
    private long checkInCount;
    private String description;
    private String websiteUrl;

    // Details Data
    private List<String> tags = new ArrayList<>();
    private List<String> types = new ArrayList<>();
    private List<String> rawContent = new ArrayList<>();
    private List<String> menuUrls = new ArrayList<>();
    private List<String> prices = new ArrayList<>();
    private double priceStart;
    private double priceEnd;

    // Contact Data
    private List<String> phoneNumbers = new ArrayList<>();
    private List<String> emails = new ArrayList<>();
    private List<SourceHour> hours = new ArrayList<>();

    // Location
    private double lat;
    private double lng;
    private String address;
    private String addressExt;
    private String street;
    private String city;
    private String state;
    private String unitNumber;
    private String zipCode;
    private String country;

    // Ratings
    private double ratingPercent;
    private int reviewCount;

    // Other Struct
    private List<SourcePost> posts = new ArrayList<>();
    private List<SourceComment> comments = new ArrayList<>();

    // Tracking
    private String trackingId;
    private int source;
    private String sourceUrl;
    private Date updatedDate;

    // Source Confirmed Status
    private int sourceConfirmation;

    // For Dashboard to rank
    private double score;

    /**
     * All data should be named with the version that is introduced
     * For data not named, it is there since VERSION_FIRST
     */
    public SourcePlace() {
        super(VERSION_FIRST);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getFanCount() {
        return fanCount;
    }

    public void setFanCount(long fanCount) {
        this.fanCount = fanCount;
    }

    public long getCheckInCount() {
        return checkInCount;
    }

    public void setCheckInCount(long checkInCount) {
        this.checkInCount = checkInCount;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getWebsiteUrl() {
        return websiteUrl;
    }

    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl;
    }

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public List<String> getTypes() {
        return types;
    }

    public void setTypes(List<String> types) {
        this.types = types;
    }

    public List<String> getRawContent() {
        return rawContent;
    }

    public void setRawContent(List<String> rawContent) {
        this.rawContent = rawContent;
    }

    public List<String> getMenuUrls() {
        return menuUrls;
    }

    public void setMenuUrls(List<String> menuUrls) {
        this.menuUrls = menuUrls;
    }

    public List<String> getPrices() {
        return prices;
    }

    public void setPrices(List<String> prices) {
        this.prices = prices;
    }

    public double getPriceStart() {
        return priceStart;
    }

    public void setPriceStart(double priceStart) {
        this.priceStart = priceStart;
    }

    public double getPriceEnd() {
        return priceEnd;
    }

    public void setPriceEnd(double priceEnd) {
        this.priceEnd = priceEnd;
    }

    public List<String> getPhoneNumbers() {
        return phoneNumbers;
    }

    public void setPhoneNumbers(List<String> phoneNumbers) {
        this.phoneNumbers = phoneNumbers;
    }

    public List<String> getEmails() {
        return emails;
    }

    public void setEmails(List<String> emails) {
        this.emails = emails;
    }

    public List<SourceHour> getHours() {
        return hours;
    }

    public void setHours(List<SourceHour> hours) {
        this.hours = hours;
    }

    public double getLat() {
        return lat;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

    public double getLng() {
        return lng;
    }

    public void setLng(double lng) {
        this.lng = lng;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAddressExt() {
        return addressExt;
    }

    public void setAddressExt(String addressExt) {
        this.addressExt = addressExt;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getUnitNumber() {
        return unitNumber;
    }

    public void setUnitNumber(String unitNumber) {
        this.unitNumber = unitNumber;
    }

    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public double getRatingPercent() {
        return ratingPercent;
    }

    public void setRatingPercent(double ratingPercent) {
        this.ratingPercent = ratingPercent;
    }

    public int getReviewCount() {
        return reviewCount;
    }

    public void setReviewCount(int reviewCount) {
        this.reviewCount = reviewCount;
    }

    public List<SourcePost> getPosts() {
        return posts;
    }

    public void setPosts(List<SourcePost> posts) {
        this.posts = posts;
    }

    public List<SourceComment> getComments() {
        return comments;
    }

    public void setComments(List<SourceComment> comments) {
        this.comments = comments;
    }

    public String getTrackingId() {
        return trackingId;
    }

    public void setTrackingId(String trackingId) {
        this.trackingId = trackingId;
    }

    public int getSource() {
        return source;
    }

    public void setSource(int source) {
        this.source = source;
    }

    public String getSourceUrl() {
        return sourceUrl;
    }

    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public int getSourceConfirmation() {
        return sourceConfirmation;
    }

    public void setSourceConfirmation(int sourceConfirmation) {
        this.sourceConfirmation = sourceConfirmation;
    }

    public double getScore() {
        return score;
    }

    public void setScore(double score) {
        this.score = score;
    }

    @Transient
    @JsonIgnore
    public String getAvailableAddress() {
        if (StringUtils.isNotEmpty(address)) {
            if (StringUtils.isNoneEmpty(address, addressExt)) {
                return address + " " + addressExt;
            }
            return address;
        }
        if (StringUtils.isNoneEmpty(street)) {
            return street;
        }
        return null;
    }
}
