version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
  postgres:
    image: postgres:9-alpine
    environment:
      - POSTGRES_PASSWORD=K851xsSffyTJP3e1M7rd
  places:
    image: munch-core/munch-service-places:latest
    environment:
      - DOCUMENT_DATABASE_URL=jdbc:postgresql://postgres:5432/postgres
      - DOCUMENT_DATABASE_USERNAME=postgres
      - DOCUMENT_DATABASE_PASSWORD=K851xsSffyTJP3e1M7rd
      - DOCUMENT_DATABASE_AUTO_CREATE=true

      - SEARCH_DATABASE_HOSTNAME=elasticsearch
    links:
      - postgres
      - elasticsearch
  catalyst:
    image: munch-core/munch-catalyst:latest
    environment:
      - CATALYST_URL=http://catalyst.munch.space:8201
      - CATALYST_USER=catalyst
      - CATALYST_PASSWORD=bq1Enf1p32pTEvqzLz9OrtXtXsEWFhU5cO9Eoww9

      - MUNCH_SERVICE_PLACES_URL=http://places:8000
    links:
      - places