version: '2'

services:
  # Corpus Proxy
  corpus-db:
    image: postgres:9-alpine
    environment:
      - POSTGRES_PASSWORD=K851xsSffyTJP3e1M7rd
  corpus-data:
    image: 197547471367.dkr.ecr.ap-southeast-1.amazonaws.com/corpus-catalyst/service-data:latest
    environment:
      - DATABASE_URL=jdbc:postgresql://corpus-db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=K851xsSffyTJP3e1M7rd
      - DATABASE_AUTO_CREATE=true
    ports:
      - "8222:8000"
  corpus-proxy:
    image: 197547471367.dkr.ecr.ap-southeast-1.amazonaws.com/corpus-catalyst/corpus-proxy:latest
    environment:
      - SERVICE_DATA_URL=http://corpus-data:8000

  # Munch Services of Services
  munch-db:
    image: postgres:9-alpine
    environment:
      - POSTGRES_PASSWORD=K851xsSffyTJP3e1M7rd
  munch-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200
  thumbor:
    image: apsl/thumbor
  fake-s3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"

  # Munch Services
  images:
    image: munch-core/service-images
    environment:
      - IMAGE_PERSIST_PROVIDER=fake

      - IMAGE_THUMBOR_ENDPOINT=http://thumbor:8000
      - IMAGE_FAKE_S3_ENDPOINT=http://fake-s3:4569
      - IMAGE_FAKE_S3_PUBLIC_ENDPOINT=http://localhost:4569
  places:
    image: munch-core/service-places
    environment:
      - DOCUMENT_DATABASE_URL=jdbc:postgresql://munch-db:5432/postgres
      - DOCUMENT_DATABASE_USERNAME=postgres
      - DOCUMENT_DATABASE_PASSWORD=K851xsSffyTJP3e1M7rd
      - DOCUMENT_DATABASE_AUTO_CREATE=true
      - SEARCH_DATABASE_HOSTNAME=munch-es
  gallery:
    image: munch-core/service-gallery
    environment:
      - DATABASE_URL=jdbc:postgresql://munch-db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=K851xsSffyTJP3e1M7rd
      - DATABASE_AUTO_CREATE=true
  articles:
    image: munch-core/service-articles
    environment:
      - DATABASE_URL=jdbc:postgresql://munch-db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=K851xsSffyTJP3e1M7rd
      - DATABASE_AUTO_CREATE=true
      - MUNCH_SERVICE_IMAGES_URL=http://images:8000

  # Munch Catalyst
  munch-catalyst:
    image: munch-core/catalyst-munch:latest
    environment:
      - SERVICE_DATA_URL=http://corpus-data:8000
      - MUNCH_SERVICE_PLACES_URL=http://places:8000
      - MUNCH_SERVICE_ARTICLES_URL=http://articles:8000
      - MUNCH_SERVICE_GALLERY_URL=http://gallery:8000

  # Location Service For Munch
  location:
    image: munch-core/service-location:latest

  # Munch Api
  munch-api:
    image: munch-core/munch-api:latest
    environment:
      - MUNCH_SERVICE_PLACES_URL=http://places:8000
      - MUNCH_SERVICE_ARTICLES_URL=http://articles:8000
      - MUNCH_SERVICE_GALLERY_URL=http://gallery:8000

      - MUNCH_SERVICE_LOCATION_URL=http://location:8000
      - MUNCH_SERVICE_IMAGES_URL=http://images:8000
    ports:
      - "8800:8000"



