FROM node:8.12.0-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json yarn.lock /usr/src/app/
RUN yarn --pure-lockfile

COPY . /usr/src/app/

ENV API_URL_BROWSER https://www.munch.app/
ENV API_MUNCH_APP https://api.munch.app/v0.14.0

ENV HOST 0.0.0.0
ENV NODE_ENV production
ENV ORIGIN https://www.munch.app
EXPOSE 3000

# Remove pages disabled for production
RUN rmdir /usr/src/app/pages/feed

RUN yarn run build
CMD [ "yarn", "run", "start" ]
